### ISSUE TITLE
Compile errors with current on CentOS7

### ISSUE THREAD

**Issue by mzi77** [aabc/ipt-netflow#48] opened 2015-11-21 08:21 UTC
Hello.

I have compilation issues with head on CentOS7 kernel 3.10.0-229.20.1.el7.x86_64

Compile log attached

[ipt-makelog.txt](https://github.com/aabc/ipt-netflow/files/40764/ipt-makelog.txt)

**Comment by aabc** [comment] 2015-11-21 12:54
Thanks. It seems to be related to 93160e54ef6a40c8daf5c07b0bb4be99ffb70857. I will look at it a bit later.

**Comment by mzi77** [comment] 2015-11-22 09:32
Great, thank you.

**Comment by aabc** [comment] 2015-11-22 16:33
Btw, I'm unable to reproduce:
```
root@el7:~/ipt-netflow# ./configure
Kernel version: 3.10.0-229.20.1.el7.x86_64 (uname)
Kernel sources: /lib/modules/3.10.0-229.20.1.el7.x86_64/build (found)
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.4.21 (detected from /usr/sbin/iptables)
pkg-config for version 1.4.21 exists: Yes
Checking for presence of xtables.h... make
Yes (using pkg-config)
Iptables include flags:   (pkg-config)
Iptables module path: /usr/lib64/xtables (pkg-config)
Searching for net-snmp-config... Yes /usr/bin/net-snmp-config
Searching for net-snmp agent... Yes.
Checking for DKMS... Yes.
Creating Makefile.. done.

  If you need some options enabled run ./configure --help
  Now run: make all install

root@el7:~/ipt-netflow# make
Compiling for kernel 3.10.0-229.20.1.el7.x86_64
make -C /lib/modules/3.10.0-229.20.1.el7.x86_64/build M=/root/ipt-netflow modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory `/usr/src/kernels/3.10.0-229.20.1.el7.x86_64'
  CC [M]  /root/ipt-netflow/ipt_NETFLOW.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/ipt-netflow/ipt_NETFLOW.mod.o
  LD [M]  /root/ipt-netflow/ipt_NETFLOW.ko
make[1]: Leaving directory `/usr/src/kernels/3.10.0-229.20.1.el7.x86_64'
root@el7:~/ipt-netflow#
```

Probably, you are not usnig get version, right?

**Comment by mzi77** [comment] 2015-11-22 19:07
I tried basic

./configure
make

which works, as you are reporting, but problems I'm getting are from

./configure --enable-vlan --enable-promisc --promisc-mpls 
make
as you can see in my makelog from first post

just tested on clean installed CentOS7 3.10.0-229.20.1.el7.x86_64
and git clone https://github.com/aabc/ipt-netflow.git

**Comment by aabc** [comment] 2015-11-22 19:41
I wasn't attentive, thanks. FIxed now.

**Comment by mzi77** [comment] 2015-11-23 07:47
I can compile head now. Thank you for fast fixing.

**Closed** 2015-11-23 08:02 UTC
Labels: compilation
