### ISSUE TITLE
port destination not applied 

### ISSUE THREAD

**Issue by ya-zero** [aabc/ipt-netflow#111] opened 2019-02-26 07:19 UTC
```bash
cat /proc/net/stat/ipt_netflow
ipt_NETFLOW 2.3-5-g940c61a
sock0: 192.168.0.4:2055
sock1: 192.168.0.40:2055
sock2: 192.168.0.12:2055
sock3: 192.168.0.43:9996
```
modules load
```bash
options ipt_NETFLOW  destination=192.168.0.4:9996,192.168.0.40:9996,192.168.0.12:9996,192.168.0.43:9996 inactive_timeout=10 active_timeout=15 sndbuf=65000
```
в sysctl -a | grep netflow
```bash
net.netflow.destination = 192.168.0.4:9996,192.168.0.40:9996,192.168.0.12:9996,192.168.0.43:9996
```

dmesg
```bash
[63634.738848] ipt_NETFLOW: added destination 192.168.0.4:2055
[63634.738856] ipt_NETFLOW: added destination 192.168.0.40:2055
[63634.738878] ipt_NETFLOW: added destination 192.168.0.12:2055
[63634.738884] ipt_NETFLOW: added destination 192.168.0.43:9996
```

**Comment by metti-himself** [comment] 2019-02-26 10:41
I have the same problem, if you take a look in /proc/sys/net/netflow/destination the entries are correctly:
cat /proc/sys/net/netflow/destination
x.x.x.x:2100,x.x.x.x:3005
But only the last entry got the port right
cat /proc/net/stat/ipt_netflow
ipt_NETFLOW 2.2, srcversion 3DB5E35CB22CC537C8DD334
sock0: x.x.x.x:2055
sock1: x.x.x.x:3005

**Comment by aabc** [comment] 2019-02-26 12:31
What kernel version you have?

**Comment by metti-himself** [comment] 2019-02-26 12:35
Kernel 4.14.14 on CentOS 7.6.1810

**Comment by aabc** [comment] 2019-02-26 12:42
Thanks. Problem is introduced by commit 940c61a29b460fe099eb8be16021136678145c4c by @dbugnar

**Comment by xtaran** [comment] 2019-02-26 12:47
> Thanks. Problem is introduced by commit [940c61a](https://github.com/aabc/ipt-netflow/commit/940c61a29b460fe099eb8be16021136678145c4c) by @dbugnar

But that only has been committed recently (November 2018) while @metti-himself said, he uses ipt_NETFLOW 2.2, which is from Februar 2016.

**Comment by aabc** [comment] 2019-02-26 13:21
`2.2` is version tag that git `master` and even release 2.3 have (forgot to increment), it's shown when people build from the tarball and not from git. So @metti-himself highly likely have version with the commit.

Let's wait for a day for @dbugnar reaction, after which I will revert the commit.

**Comment by dbugnar** [comment] 2019-02-26 21:28
I checked the code and fixed the issue. The PR is open.

**Comment by ya-zero** [comment] 2019-02-28 07:39
problem not fixed
```bash
ipt_NETFLOW 2.3-10-g266380e, srcversion E6E904647A90A3DDC403934; llist
Protocol version 5 (netflow)
Timeouts: active 15s, inactive 10s. Maxflows 2000000
Flows: active 1 (peak 4 reached 0d0h1m ago), mem 5120K, worker delay 25/250 [1..25] (48 ms, 0 us, 1:0 0 [cpu3]).
Hash: size 655360 (mem 5120K), metric 1.00 [1.00, 1.00, 1.00]. InHash: 5 pkt, 0 K, InPDU 23, 1572.
Rate: 480 bits/sec, 1 packets/sec; Avg 1 min: 701 bps, 0 pps; 5 min: 552 bps, 0 pps
cpu#     pps; <search found new [metric], trunc frag alloc maxflows>, traffic: <pkt, bytes>, drop: <pkt, bytes>
Total      1;      0    354     44 [1.00],    0    0    0    0, traffic: 398, 0 MB, drop: 0, 0 K
cpu8       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu9       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu10      0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu11      0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
Export: Rate 0 bytes/s; Total 76 pkts, 0 MB, 41 flows; Errors 0 pkts; Traffic lost 0 pkts, 0 Kbytes, 0 flows.
sock0: 192.168.0.4:2055, sndbuf 65000, filled 1, peak 1281; err: sndbuf reached 0, connect 0, cberr 19, other 0
sock1: 192.168.0.40:2055, sndbuf 65000, filled 1, peak 1281; err: sndbuf reached 0, connect 0, cberr 19, other 0
sock2: 192.168.0.12:2055, sndbuf 65000, filled 1, peak 1281; err: sndbuf reached 0, connect 0, cberr 19, other 0
sock3: 192.168.0.43:9996, sndbuf 65000, filled 1, peak 1281; err: sndbuf reached 0, connect 0, cberr 0, other 0
```

**Comment by dbugnar** [comment] 2019-02-28 08:25
@ya-zero did you include also the commits from the PR? 
The PR is currently open and the commits are not in the repo.

**Comment by ya-zero** [comment] 2019-02-28 08:58
no. i'm download new version : git clone repo.

**Comment by metti-himself** [comment] 2019-02-28 11:01
I cloned from @dbugnar  repo, in my test setup the issue is fixed:
sock0: 127.0.0.1:3005
sock1: 127.0.0.1:2100

Kernel 4.19.21
cat /proc/sys/net/netflow/destination
127.0.0.1:3005,127.0.0.1:2100

Thanks for the quick fix.

**Comment by ya-zero** [comment] 2019-02-28 14:15
clone from @dbugnar repo is fixed
```bash
ipt_NETFLOW 2.3-12-g725ff79, srcversion 6A554176B8E738D80AB5D5E; llist
Protocol version 5 (netflow)
Timeouts: active 15s, inactive 10s. Maxflows 2000000
Flows: active 0 (peak 0 reached 0d0h0m ago), mem 5120K, worker delay 25/250 [1..25] (8 ms, 0 us, 0:0 0 [cpu7]).
Hash: size 655360 (mem 5120K), metric 1.00 [1.00, 1.00, 1.00]. InHash: 0 pkt, 0 K, InPDU 0, 0.
Rate: 0 bits/sec, 0 packets/sec; Avg 1 min: 0 bps, 0 pps; 5 min: 0 bps, 0 pps
cpu#     pps; <search found new [metric], trunc frag alloc maxflows>, traffic: <pkt, bytes>, drop: <pkt, bytes>
Total      0;      0      0      0 [0.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu0       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu1       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu2       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu3       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu4       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu5       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu6       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu7       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu8       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu9       0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu10      0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
cpu11      0;      0      0      0 [1.00],    0    0    0    0, traffic: 0, 0 MB, drop: 0, 0 K
Export: Rate 0 bytes/s; Total 0 pkts, 0 MB, 0 flows; Errors 0 pkts; Traffic lost 0 pkts, 0 Kbytes, 0 flows.
sock0: 192.168.0.4:9996, sndbuf 65000, filled 1, peak 0; err: sndbuf reached 0, connect 0, cberr 0, other 0
sock1: 192.168.0.40:9996, sndbuf 65000, filled 1, peak 0; err: sndbuf reached 0, connect 0, cberr 0, other 0
sock2: 192.168.0.12:9996, sndbuf 65000, filled 1, peak 0; err: sndbuf reached 0, connect 0, cberr 0, other 0
sock3: 192.168.0.43:9996, sndbuf 65000, filled 1, peak 0; err: sndbuf reached 0, connect 0, cberr 0, other 0
```

**Closed** 2019-03-02 18:35 UTC

**Comment by aabc** [comment] 2019-03-02 18:39
dbugnar's fixes are merged into the master. I would appreciate your final test.

**Comment by metti-himself** [comment] 2019-03-05 13:07
@aabc @dbugnar  successfully tested with 4.19.21 on CentOS7.

**Comment by aabc** [comment] 2019-03-05 13:14
Thanks much!
